name: My Workflow

on: push

jobs:
  Update_image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Jfrog
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: the-maux
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Update Docker image in GHCR
      uses: actions/checkout@v3
      run: |
        docker build --label "org.opencontainers.image.source=https://github.com/the-maux/Recon4Poor" -t ghcr.io/the-maux/recoon4poor:latest .
        docker push ghcr.io/the-maux/recoon4poor:latest

# i don't remember why we need the --label, (linked to GHCR i think)
#     if: startsWith(github.event.head_commit.message, 'BUILD')
  Test_and_coverage_project:
    runs-on: ubuntu-latest
    needs: [Update_image]
    container:
      image: ghcr.io/the-maux/recoon4poor:latest
      env:
        COVERAGE: True
    steps:
    - uses: actions/checkout@v3
    - name: Start the scan from docker image
      run: |
        python src/unit_test.py

#    if: startsWith(github.event.head_commit.message, 'SCAN')
  Scan_a_target:
    runs-on: ubuntu-latest
    needs: [Test_project]
    container:
      image: ghcr.io/the-maux/recoon4poor:latest
      env:
        COVERAGE: False
        TARGET: ${{ secrets.TARGET }}
        DEPTH: 1
    steps:
    - uses: actions/checkout@v3
    - name: Start the scan from docker image
      run: |
        python src/main.py
