#name: Start Scan on target
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  Scanning:
#
#    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/the-maux/recoon4poor:0.0.1
#      options: -v ${{ github.workspace }}:/opt/app
#      credentials:
#        username: ${{ github.actor }}
#        password: ${{ secrets.SVC_TOKEN }}
#    env:
#      GITHUB_PASSWD: ${{ secrets.GITHUB_TOKEN }}
#      USER_EMAIL: ${{ secrets.USER_EMAIL }}
#      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
#      CHAOS_KEY: ${{ secrets.CHAOS_KEY }}
#      TARGET: ${{ secrets.TARGET }}
#      DEPTH: ${{ secrets.DEPTH }}
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Start the scan from docker image
#        run: |
#          python src/main.py

