name: Start Scan on target

on:
  push:
    branches:
      - develop

jobs:
  Scanning:
#    if: startsWith(github.event.head_commit.message, 'SCAN')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/the-maux/recoon4poor:latest
      options: -v ${{ github.workspace }}:/opt/app
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    env:
      GITHUB_PASSWD: ${{ secrets.GITHUB_TOKEN }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      CHAOS_KEY: ${{ secrets.CHAOS_KEY }}
      TARGET: ${{ secrets.TARGET }}
      DEPTH: ${{ secrets.DEPTH }}
    steps:
      - uses: actions/checkout@v1
      - name: Start the scan from docker image
        run: |
          python src/main.py

#        docker run -e GITHUB_PASSWD="${{ secrets.GITHUB_TOKEN }}" \
#                -e USER_EMAIL="${{ secrets.USER_EMAIL }}" \
#                -e USER_PASSWORD="${{ secrets.USER_PASSWORD }}" \
#                -e CHAOS_KEY="${{ secrets.CHAOS_KEY }}" \
#                -e TARGET="${{ secrets.TARGET }}" \
#                -e DEPTH="${{ secrets.DEPTH }}" \
#                ghcr.io/the-maux/recoon4poor:0.0.1
