name: Recon4Poor # all credits to KathanP19 -> https://github.com/KathanP19/Recon4Poor <3

on: [push]

jobs:
  Scanning:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Start the scan from docker image
      run: |  # TODO: error gestion to notify when env var not present
        docker build -t scan:local .
        docker run -e GITHUB_PASSWD="${{ secrets.GITHUB_TOKEN }}" \
        -e USER_EMAIL="${{ secrets.USER_EMAIL }}" \
        -e USER_PASSWORD="${{ secrets.USER_PASSWORD }}" \
        -e CHAOS_KEY="${{ secrets.CHAOS_KEY }}" \
        scan:local

