name: Test the code

on: push

jobs:
  Test_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start the scan from docker image
        run: |
        docker build -t recoon4poor:testing .          
        docker run recoon4poor:testing python src/unit_test.py
