name: Create PR

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branche-cible:
        description: 'Nom de la branch qui va etre créé'
        required: true
        default: 'XXX-alpha'
        type: string
      branche-source:
        description: 'Nom de la branch qui va etre la source'
        required: true
        default: 'main'
        type: string
      repository-name:
        description: 'Nom du repository'
        required: true
        default: 'enki-devops-scripts'
        type: string

jobs:
  create_PR:
    runs-on: [self-hosted, Linux, service]
    steps:

      - name: Test print
        run: |
          echo "Variable is ${{ inputs.repository-name }}"

      - name: Créer la Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          commit-message: "Merge branche ${{ inputs.branche-source }}"
          title: "Merge branch ${{ inputs.branche-source }} -> ${{ inputs.branche-cible }}"
          body: "Cette Pull Request merge la branche ${{ inputs.branche-source }} dans la branche cible"
          branch: ${{ inputs.branche-source }}
          base: ${{ inputs.branche-cible }}
          repository: ${{ inputs.repository-name }}

# - name: Créer la Pull Request
#        run: |
#          # Récupérer les informations nécessaires
#          REPO=${{ github.event.inputs.repo }}
#          SOURCE_BRANCH=${{ github.event.inputs.branche-source }}
#          TARGET_BRANCH=${{ github.event.inputs.branche-cible }}
#
#          # Créer la Pull Request en utilisant l'API GitHub
#          RESPONSE=$(curl -X POST \
#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            -d '{
#              "title": "Merge de la branche '"$SOURCE_BRANCH"'",
#              "body": "Cette Pull Request fusionne la branche '"$SOURCE_BRANCH"' dans la branche cible",
#              "head": "'"$SOURCE_BRANCH"'",
#              "base": "'"$TARGET_BRANCH"'"
#            }' \
#            "https://api.github.com/repos/${{ github.event.inputs.repository }}/pulls")
#
#          # Extraire l'URL de la Pull Request créée
#          PR_URL=$(echo "$RESPONSE" | jq -r '.html_url')
#
#          echo "Pull Request créée : $PR_URL"