name: Update image dependency

on:
  push:
    branches:
      - develop

jobs:
  GHCR_Update:

    runs-on: ubuntu-latest
    steps:
    - if: startsWith(github.event.head_commit.message, 'BUILD')
    - uses: actions/checkout@v1

    - name: Update Docker image in GHCR
      run: |
        echo "${{ secrets.SVC_TOKEN }}" | sudo docker login ghcr.io --username the-maux --password-stdin
        docker build -t --label "org.opencontainers.image.source=https://github.com/the-maux/Recon4Poor" ghcr.io/the-maux/recoon4poor:0.0.1 .
        docker push ghcr.io/the-maux/recoon4poor:latest
