name: 1- Update docker image

on: push

jobs:
  GHCR_Update:
#    if: startsWith(github.event.head_commit.message, 'BUILD')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Docker image in GHCR
      run: |
        echo -n "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u the-maux --password-stdin
        echo -n "${{ secrets.DOCKER_TOKEN }}" | docker login -u themaux --password-stdin
        docker build --label "org.opencontainers.image.source=https://github.com/the-maux/Recon4Poor" -t ghcr.io/the-maux/recoon4poor:latest .
        docker tag ghcr.io/the-maux/recoon4poor:latest themaux/recoon:latest 
        docker push ghcr.io/the-maux/recoon4poor:latest
        docker push themaux/recoon:latest 
